[env]
TERM = "xterm-256color"

[general]
import = [
    "~/.config/alacritty/themes/themes/dark_pastels.toml"
]

[font]
size = 11

[font.normal]
family = "GeistMono Nerd Font Mono"
style = "Regular"

[window]
opacity = 0.4

[window.padding]
x = 10
y = 0

[terminal.shell]
program = "/bin/bash"
