[env]
TERM = "xterm-256color"

[font]
size = 11

[font.normal]
family = "GeistMono Nerd Font Mono"
style = "Regular"

[window]
opacity = 0.5

[window.padding]
x = 10
y = 0

[terminal.shell]
program = "/bin/bash"
